-- AlterTable
ALTER TABLE "Beat" ADD COLUMN IF NOT EXISTS "s3MasterUrl" TEXT;
ALTER TABLE "Beat" ADD COLUMN IF NOT EXISTS "s3StemsUrl" TEXT;
ALTER TABLE "Beat" ADD COLUMN IF NOT EXISTS "s3MasterKey" TEXT;
ALTER TABLE "Beat" ADD COLUMN IF NOT EXISTS "s3StemsKey" TEXT;
